[package]
authors = ["William Gough <williamhenrygough@gmail.com>"]
edition = "2018"
name = "rust"
version = "0.1.0"
[dependencies]
fxhash = "*"
geo = "*"
itertools = "*"
lazy_static = "1.4.0"
regex = "1.4.2"
